version: '3.8'

services:
 flask:
  restart: always
  environment:
  - FLASK_ENV=production

 mysqldb:
  restart: always
  environment:
  # - MYSQL_ROOT_PASSWORD=
  - MYSQL_RANDOM_ROOT_PASSWORD=yes
  - MYSQL_PASSWORD=mcp_password
  - MYSQL_DATABASE=master_control_program

 redis:
  restart: always

 rqworker:
  restart: always

 nginx:
  build: nginx
  restart: always
  ports:
  - 80:80
  - 443:443
