"""empty message

Revision ID: 338769bb4f87
Revises: 5563e04221bb
Create Date: 2021-01-14 16:47:33.370713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338769bb4f87'
down_revision = '5563e04221bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('background_check_date', sa.DateTime(), nullable=True))
    op.add_column('wildapricot_user', sa.Column('last_sync_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wildapricot_user', 'last_sync_time')
    op.drop_column('user', 'background_check_date')
    # ### end Alembic commands ###
